Repository metadevpro/lux, pull requests merged in 2021-09, with the labels that each got.

#132 Feature/enhance autocomplete
  projects/lux/src/lib/assets/img/spinner.svg
  projects/lux/src/lib/assets/img/suggestions.svg
  projects/lux/src/lib/autocomplete/autocomplete.component.html
  projects/lux/src/lib/autocomplete/autocomplete.component.scss
  projects/lux/src/lib/autocomplete/autocomplete.component.ts
  src/app/autocomplete-sample/autocomplete-sample.component.html
  src/app/autocomplete-sample/autocomplete-sample.component.ts
  src/assets/img/spinner.svg
  src/assets/img/suggestions.svg
Labels: enhancement

#137 Make tooltip documentation match examples
  src/app/tooltip-sample/tooltip-sample.component.html
Labels: documentation

#139 fix #138 touched on blur
  projects/lux/src/lib/input/input.component.html
  projects/lux/src/lib/input/input.component.ts
Labels: bug

#143 Handle set value to null
  projects/lux/src/lib/geolocation/geolocation.component.ts
Labels: bug

#147 Document instructions to debug in target app
  README.md
Labels: documentation
